---
- name: Create AWS GPU Instance
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/main.yml

  tasks:
    - name: Find private AMI by name
      amazon.aws.ec2_ami_info:
        filters:
          name: "{{ ami_name }}"
          state: available
        owners: "{{ ami_owner_id }}"
        region: "{{ aws_region }}"
        profile: "{{ aws_profile }}"
      register: ami_info

    - name: Fail if no AMI found
      fail:
        msg: "No AMI found with name '{{ ami_name }}'. Please check the AMI name and try again."
      when: ami_info.images | length == 0

    - name: Create security group without any rules
      amazon.aws.ec2_security_group:
        name: "{{ instance_name }}-sg"
        description: Security group for {{ instance_name }}
        region: "{{ aws_region }}"
        profile: "{{ aws_profile }}"
        state: present
      register: security_group

    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        image_id: "{{ ami_info.images[0].image_id }}"
        instance_type: "{{ instance_type }}"
        security_groups: "{{ security_group.group_name }}"
        iam_instance_profile: "{{ iam_instance_profile }}"
        tags:
          Name: "{{ instance_name }}"
          role: gpu-dev-instance
        volumes:
          - device_name: /dev/xvda
            ebs:
              volume_size: "{{ volume_size }}"
              volume_type: "{{ volume_type }}"
        region: "{{ aws_region }}"
        profile: "{{ aws_profile }}"
        state: present
        wait: yes
      register: ec2

    - name: Wait for instance to be in running state
      amazon.aws.ec2_instance_info:
        instance_ids:
          - "{{ ec2.instances[0].instance_id }}"
        region: "{{ aws_region }}"
        profile: "{{ aws_profile }}"
      register: instance_info
      until: instance_info.instances[0].state.name == "running"
      retries: 30
      delay: 10

    - name: Print instance information
      debug:
        msg:
          - "Instance Name: {{ instance_info.instances[0].tags.Name }}"
          - "Instance ID: {{ instance_info.instances[0].instance_id }}"
          - "Status: {{ instance_info.instances[0].state.name }}"
          - "Instance Type: {{ instance_info.instances[0].instance_type }}"
          - "Role: {{ instance_info.instances[0].tags.role }}"

    - name: Wait for instance to be running
      community.aws.ec2_instance_info:
        instance_ids:
          - "{{ ec2.instances[0].instance_id }}"
        region: "{{ aws_region }}"
      register: instance_info
      until: instance_info.instances[0].state.name == "running"
      retries: 30
      delay: 10

    - name: Create SSM document for starting instance
      community.aws.ssm_document:
        name: "{{ username }}-start-instance"
        document_type: Command
        content: |
          {
            "schemaVersion": "2.2",
            "description": "Start EC2 instance",
            "mainSteps": [
              {
                "action": "aws:runShellScript",
                "name": "startInstance",
                "inputs": {
                  "runCommand": [
                    "aws ec2 start-instances --instance-ids {{ ec2.instances[0].instance_id }} --profile {{ aws_profile }}"
                  ]
                }
              }
            ]
          }
        state: present
        region: "{{ aws_region }}"
      when: ec2_schedule

    - name: Create SSM document for stopping instance
      community.aws.ssm_document:
        name: "{{ username }}-stop-instance"
        document_type: Command
        content: |
          {
            "schemaVersion": "2.2",
            "description": "Stop EC2 instance",
            "mainSteps": [
              {
                "action": "aws:runShellScript",
                "name": "stopInstance",
                "inputs": {
                  "runCommand": [
                    "aws ec2 stop-instances --instance-ids {{ ec2.instances[0].instance_id }} --profile {{ aws_profile }}"
                  ]
                }
              }
            ]
          }
        state: present
        region: "{{ aws_region }}"
      when: ec2_schedule

    - name: Create EventBridge rule for starting instance
      community.aws.events_rule:
        name: "{{ username }}-start-instance-rule"
        schedule_expression: "cron({{ schedule_start }})"
        state: present
        region: "{{ aws_region }}"
      when: ec2_schedule

    - name: Create EventBridge rule for stopping instance
      community.aws.events_rule:
        name: "{{ username }}-stop-instance-rule"
        schedule_expression: "cron({{ schedule_stop }})"
        state: present
        region: "{{ aws_region }}"
      when: ec2_schedule

    - name: Add target to start instance rule
      community.aws.events_target:
        rule: "{{ username }}-start-instance-rule"
        target_id: "{{ username }}-start-instance-target"
        arn: "arn:aws:ssm:{{ aws_region }}:{{ ami_owner_id }}:document/{{ username }}-start-instance"
        state: present
        region: "{{ aws_region }}"
      when: ec2_schedule

    - name: Add target to stop instance rule
      community.aws.events_target:
        rule: "{{ username }}-stop-instance-rule"
        target_id: "{{ username }}-stop-instance-target"
        arn: "arn:aws:ssm:{{ aws_region }}:{{ ami_owner_id }}:document/{{ username }}-stop-instance"
        state: present
        region: "{{ aws_region }}"
      when: ec2_schedule 