---
- name: Remove AWS GPU Instance
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/main.yml

  tasks:
    - name: Terminate EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        region: "{{ aws_region }}"
        profile: "{{ aws_profile }}"
        state: absent
        wait: yes

    - name: Remove security group
      amazon.aws.ec2_security_group:
        name: "{{ instance_name }}-sg"
        region: "{{ aws_region }}"
        profile: "{{ aws_profile }}"
        state: absent 