---
- name: Setup EC2 Instance Schedule
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/main.yml

  tasks:
    - name: Create SSM document for starting instance
      community.aws.ssm_document:
        name: "{{ username }}-start-instance"
        document_type: Command
        content: |
          {
            "schemaVersion": "2.2",
            "description": "Start EC2 instance",
            "mainSteps": [
              {
                "action": "aws:runShellScript",
                "name": "startInstance",
                "inputs": {
                  "runCommand": [
                    "aws ec2 start-instances --instance-ids {{ instance_id }} --profile {{ aws_profile }}"
                  ]
                }
              }
            ]
          }
        state: present
        region: "{{ aws_region }}"
      register: start_document

    - name: Create SSM document for stopping instance
      community.aws.ssm_document:
        name: "{{ username }}-stop-instance"
        document_type: Command
        content: |
          {
            "schemaVersion": "2.2",
            "description": "Stop EC2 instance",
            "mainSteps": [
              {
                "action": "aws:runShellScript",
                "name": "stopInstance",
                "inputs": {
                  "runCommand": [
                    "aws ec2 stop-instances --instance-ids {{ instance_id }} --profile {{ aws_profile }}"
                  ]
                }
              }
            ]
          }
        state: present
        region: "{{ aws_region }}"
      register: stop_document

    - name: Get instance ID
      community.aws.ec2_instance_info:
        filters:
          "tag:Name": "{{ instance_name }}"
        region: "{{ aws_region }}"
      register: instance_info

    - name: Set instance ID fact
      set_fact:
        instance_id: "{{ instance_info.instances[0].instance_id }}"

    - name: Create EventBridge rule for starting instance
      community.aws.events_rule:
        name: "{{ username }}-start-instance-rule"
        schedule_expression: "cron({{ schedule_start }})"
        state: present
        region: "{{ aws_region }}"
      when: ec2_schedule

    - name: Create EventBridge rule for stopping instance
      community.aws.events_rule:
        name: "{{ username }}-stop-instance-rule"
        schedule_expression: "cron({{ schedule_stop }})"
        state: present
        region: "{{ aws_region }}"
      when: ec2_schedule

    - name: Add target to start instance rule
      community.aws.events_target:
        rule: "{{ username }}-start-instance-rule"
        target_id: "{{ username }}-start-instance-target"
        arn: "arn:aws:ssm:{{ aws_region }}:{{ ami_owner_id }}:document/{{ username }}-start-instance"
        state: present
        region: "{{ aws_region }}"
      when: ec2_schedule

    - name: Add target to stop instance rule
      community.aws.events_target:
        rule: "{{ username }}-stop-instance-rule"
        target_id: "{{ username }}-stop-instance-target"
        arn: "arn:aws:ssm:{{ aws_region }}:{{ ami_owner_id }}:document/{{ username }}-stop-instance"
        state: present
        region: "{{ aws_region }}"
      when: ec2_schedule 