repos:
  - repo: local
    hooks:
      - id: ruff
        name: Run ruff checks
        entry: make ruff-check
        language: python
        types: [python]
        pass_filenames: false
      - id: ruff-fix
        name: Run ruff-fix
        entry: make ruff-fix
        language: python
        types: [python]
        pass_filenames: false
