datasets:
  example-local-mlflow:
    _target_: czibench.datasets.sc.SingleCellDataset
    organism: ${organism:HUMAN}
    source_path: ~/cz-benchmarks/example_small.h5ad
  example-local-bento:
    _target_: czibench.datasets.sc.SingleCellDataset
    organism: ${organism:HUMAN}
    source_path: ~/cz-benchmarks/example_small.h5ad
  example-local-sagemaker:
    _target_: czibench.datasets.sc.SingleCellDataset
    organism: ${organism:HUMAN}
    source_path: s3://generate-cross-species/datasets/test/example_small.h5ad
  example-remote-mlflow:
    _target_: czibench.datasets.sc.SingleCellDataset
    organism: ${organism:HUMAN}
    source_path: https://generate-cross-species.s3.us-west-2.amazonaws.com/datasets/test/example_small.h5ad?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAQ3EGQGYRVH6ZHUER%2F20250228%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20250228T183824Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&X-Amz-Security-Token=FwoGZXIvYXdzEGwaDBbMwPEw0YJc9loS0CLfArCGKAqMphavpunmPlOhw%2B5Ftsoxn%2BK1Tt7QB2bmgy5dtZbwwgCipnGfWk%2FKPrB5k4az%2Bi5l4Q2VysW9m%2FHc%2BeuS%2B50neYVzfjKbXs4n0%2Ft1BPwR8aEiU3FYLYdSOv9BxIpMQ3q5Y7bX664VAaMcUMuPRdJeaVqs67arwzA43vBsM0RRKE3q2nWCrx1%2BEA6Bqo31H3WCP6Vc7LlExRxGfjNnfyA2S4HaCBFynPLCP0W1pU3vE3npksDLXRYy9H9cPPOSLRYvurHKOLNtCDi3%2BQ3s45P4Q%2FNcqlnH80l7w6gYtPmqK%2BW4RnW7ZSeGaw3r9nOcom1rIJag86wCNJqdl17yUDuvR1Gu6LhV%2BJX%2FEqXs%2FdKCngWYO0oa03XfnW2lElpBtfiyS6M1y%2BP3pOO1ofFCCshfWtS59uQHTyHOdfDiriYL8zEkmIZ3OluEmOpsXRkk0PYp8rl774foTSJWPCighYi%2BBjIlPDag1tvocLf%2FnKjpGMqF6M6Jsi7V30w2zm7mxc3ONrdpxSbPuA%3D%3D&X-Amz-Signature=56cc1dcd285cff478ce0fddda3bd73270017fe577ae32c7f7fcf2937dc17c39e
  example-remote-sagemaker:
    _target_: czibench.datasets.sc.SingleCellDataset
    organism: ${organism:HUMAN}
    source_path: s3://generate-cross-species/datasets/test/example_small.h5ad
  