defaults:
  - _self_

datasets:
  mouse_brain_atlas:
    _target_: czibench.datasets.single_cell.SingleCellDataset
    organism: ${organism:MOUSE}
    path: s3://example-bucket/datasets/mouse_brain_atlas.h5ad

  human_pbmc_10x:
    _target_: czibench.datasets.single_cell.SingleCellDataset
    organism: ${organism:HUMAN}
    path: s3://example-bucket/datasets/human_pbmc_10k.h5ad

  tsv2_bladder:
    _target_: czibench.datasets.single_cell.SingleCellDataset
    organism: ${organism:HUMAN}
    path: /mnt/efs/datasets/tabula_sapiens_2/tsp1_33/Bladder_TSP1_33_10X_smartseq_scvi_version1_may2024-026.h5ad