models:
  model_bucket: "s3://czi-scgenept-public"
  vocab_uri: "${models.model_bucket}/models/pretrained/scgpt/vocab.json"
  gene_embeddings_uri: "${models.model_bucket}/models/gene_embeddings/"
  finetuned_models_uri: "${models.model_bucket}/models/finetuned"
  scgenept_go_all__adamson: "${models.finetuned_models_uri}/scgenept_go_all/adamson"
  scgenept_go_c__adamson: "${models.finetuned_models_uri}/scgenept_go_c/adamson"
  scgenept_go_f__adamson: "${models.finetuned_models_uri}/scgenept_go_f/adamson"
  scgenept_go_p__adamson: "${models.finetuned_models_uri}/scgenept_go_p/adamson"
  scgenept_ncbi+uniprot__adamson: "${models.finetuned_models_uri}/scgenept_ncbi+uniprot/adamson"
  scgenept_ncbi__adamson: "${models.finetuned_models_uri}/scgenept_ncbi/adamson"
  scgpt__adamson: "${models.finetuned_models_uri}/scgpt/adamson"
  scgenept_go_all__norman: "${models.finetuned_models_uri}/scgenept_go_all/norman"
  scgenept_go_c__norman: "${models.finetuned_models_uri}/scgenept_go_c/norman"
  scgenept_go_f__norman: "${models.finetuned_models_uri}/scgenept_go_f/norman"
  scgenept_go_p__norman: "${models.finetuned_models_uri}/scgenept_go_p/norman"
  scgenept_ncbi+uniprot__norman: "${models.finetuned_models_uri}/scgenept_ncbi+uniprot/norman"
  scgenept_ncbi__norman: "${models.finetuned_models_uri}/scgenept_ncbi/norman"
  scgpt__norman: "${models.finetuned_models_uri}/scgpt/norman"
 