paths:
  mnt_path: /app/artifacts
  model_dir: ${paths.mnt_path}/models/uce
  embedding_dir: ${paths.mnt_path}/models/uce/protein_embeddings
  
model_config:
  model_name: 33l_8ep_1024t_1280
  adata_path: null # set in the inference script
  dir: .
  species: "human"
  filter: true
  skip: true
  model_loc: ${paths.model_dir}/33l_8ep_1024t_1280.torch
  batch_size: 40
  pad_length: 1536
  pad_token_idx: 0
  chrom_token_left_idx: 1
  chrom_token_right_idx: 2
  cls_token_idx: 3
  CHROM_TOKEN_OFFSET: 143574
  sample_size: 1024
  CXG: true
  nlayers: 33
  output_dim: 1280
  d_hid: 5120
  token_dim: 5120
  multi_gpu: false
  spec_chrom_csv_path: ${paths.model_dir}/species_chrom.csv
  token_file: ${paths.model_dir}/all_tokens.torch
  protein_embeddings_dir: ${paths.embedding_dir}
  offset_pkl_path: ${paths.model_dir}/species_offsets.pkl
