defaults:
  - _self_

datasets:
  replogle_k562_essential_perturbpredict:
    _target_: czbenchmarks.datasets.SingleCellPerturbationDataset
    organism: ${organism:HUMAN}
    condition_key: condition
    control_name: non-targeting
    de_gene_col: gene_id
    deg_test_name: wilcoxon
    path: s3://cz-benchmarks-data/datasets/v1/perturb/single_cell/replogle_k562_essential_perturbpredict_de_results_control_cells.h5ad

  human_spermatogenesis:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/evo_distance/testis/Homo_sapiens_ERP132584_droplet_based_curated.h5ad

  mouse_spermatogenesis:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:MOUSE}
    path: s3://cz-benchmarks-data/datasets/v1/evo_distance/testis/Mus_musculus_ERP132577_droplet_based_curated.h5ad

  rhesus_macaque_spermatogenesis:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:RHESUS_MACAQUE}
    path: s3://cz-benchmarks-data/datasets/v1/evo_distance/testis/Macaca_mulatta_ERP132582_droplet_based_curated.h5ad

  gorilla_spermatogenesis:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:GORILLA}
    path: s3://cz-benchmarks-data/datasets/v1/evo_distance/testis/Gorilla_gorilla_ERP132581_droplet_based_curated.h5ad

  chimpanzee_spermatogenesis:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:CHIMPANZEE}
    path: s3://cz-benchmarks-data/datasets/v1/evo_distance/testis/Pan_troglodytes_ERP139683_droplet_based_curated.h5ad

  marmoset_spermatogenesis:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:MARMOSET}
    path: s3://cz-benchmarks-data/datasets/v1/evo_distance/testis/Callithrix_jacchus_ERP132588_droplet_based_curated.h5ad

  chicken_spermatogenesis:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:CHICKEN}
    path: s3://cz-benchmarks-data/datasets/v1/evo_distance/testis/Gallus_gallus_ERP132576_droplet_based_curated.h5ad

  opossum_spermatogenesis:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:OPOSSUM}
    path: s3://cz-benchmarks-data/datasets/v1/evo_distance/testis/Monodelphis_domestica_ERP132579_droplet_based_curated.h5ad

  platypus_spermatogenesis:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:PLATYPUS}
    path: s3://cz-benchmarks-data/datasets/v1/evo_distance/testis/Ornithorhynchus_anatinus_ERP132578_droplet_based_curated.h5ad

  tsv2_bladder:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Bladder_v2_curated.h5ad

  tsv2_blood:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Blood_v2_curated.h5ad

  tsv2_bone_marrow:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Bone_Marrow_v2_curated.h5ad

  tsv2_ear:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Ear_v2_curated.h5ad

  tsv2_eye:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Eye_v2_curated.h5ad

  tsv2_fat:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Fat_v2_curated.h5ad

  tsv2_heart:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Heart_v2_curated.h5ad

  tsv2_large_intestine:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Large_Intestine_v2_curated.h5ad

  tsv2_liver:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Liver_v2_curated.h5ad

  tsv2_lung:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Lung_v2_curated.h5ad

  tsv2_lymph_node:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Lymph_Node_v2_curated.h5ad

  tsv2_mammary:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Mammary_v2_curated.h5ad

  tsv2_muscle:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Muscle_v2_curated.h5ad

  tsv2_ovary:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Ovary_v2_curated.h5ad

  tsv2_prostate:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Prostate_v2_curated.h5ad

  tsv2_salivary_gland:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Salivary_Gland_v2_curated.h5ad

  tsv2_skin:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Skin_v2_curated.h5ad

  tsv2_small_intestine:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Small_Intestine_v2_curated.h5ad

  tsv2_spleen:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Spleen_v2_curated.h5ad

  tsv2_stomach:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Stomach_v2_curated.h5ad

  tsv2_testis:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Testis_v2_curated.h5ad

  tsv2_thymus:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Thymus_v2_curated.h5ad

  tsv2_tongue:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Tongue_v2_curated.h5ad

  tsv2_trachea:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Trachea_v2_curated.h5ad

  tsv2_uterus:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Uterus_v2_curated.h5ad

  tsv2_vasculature:
    _target_: czbenchmarks.datasets.SingleCellLabeledDataset
    organism: ${organism:HUMAN}
    path: s3://cz-benchmarks-data/datasets/v1/cell_atlases/Homo_sapiens/Tabula_Sapiens_v2/homo_sapiens_10df7690-6d10-4029-a47e-0f071bb2df83_Vasculature_v2_curated.h5ad

  allen_soundlife_cd4_t_cells:
    _target_: czbenchmarks.datasets.single_cell.SingleCellDataset
    organism: ${organism:HUMAN}
    path: /data/datasets/single-cell/SoundLife/czi/eac87a3e-7243-4821-8244-dd558e20d230.h5ad

  allen_soundlife_cd8_t_cells:
    _target_: czbenchmarks.datasets.single_cell.SingleCellDataset
    organism: ${organism:HUMAN}
    path: /data/datasets/single-cell/SoundLife/czi/4b1ae172-2b43-48e8-ba0e-7cc62cd95b78.h5ad

  allen_soundlife_monocytes:
    _target_: czbenchmarks.datasets.single_cell.SingleCellDataset
    organism: ${organism:HUMAN}
    path: /data/datasets/single-cell/SoundLife/czi/4ce0b6ee-f388-439a-b403-1046224eb74c.h5ad

  allen_soundlife_b_and_plasma_cells:
    _target_: czbenchmarks.datasets.single_cell.SingleCellDataset
    organism: ${organism:HUMAN}
    path: /data/datasets/single-cell/SoundLife/czi/52b013d7-21d5-4c0f-a8ea-af6abdcc045b.h5ad

  allen_soundlife_nk_cells_and_ilcs:
    _target_: czbenchmarks.datasets.single_cell.SingleCellDataset
    organism: ${organism:HUMAN}
    path: /data/datasets/single-cell/SoundLife/czi/2fd624a4-55f0-4877-99f9-e04b4a89b8b5.h5ad

  allen_soundlife_dcs:
    _target_: czbenchmarks.datasets.single_cell.SingleCellDataset
    organism: ${organism:HUMAN}
    path: /data/datasets/single-cell/SoundLife/czi/33929345-ded7-470b-9947-68c0223625ba.h5ad

  allen_soundlife_other_cells:
    _target_: czbenchmarks.datasets.single_cell.SingleCellDataset
    organism: ${organism:HUMAN}
    path: /data/datasets/single-cell/SoundLife/czi/0712266c-8a39-4b8f-842b-3b6c75a8215e.h5ad
