name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write # to authenticate as Trusted Publisher to pypi.org
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: pip install build
      - run: python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # TODO: Once the repo is public, switch to publishing via Trusted Publisher and remove the test token
          password: ${{ secrets.TEST_PYPI_CZI_API_TOKEN }}
          repository-url: https://testpypi.org/legacy/
