name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black==24.8.0 flake8==7.0.0 autoflake==2.2.1 ruff==0.9.8 mypy==1.9.0
    - name: Run black
      run: make black-check
    - name: Run ruff
      run: make ruff-check
    - name: Run mypy
      run: make mypy-check
