name: CI testing

on:
  push:
    branches: [ main ]
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
      - '[0-9]+\.[0-9]+\.[0-9]+-*'
  pull_request:
    branches: [ main ]

jobs:
  run_tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python: [ '3.10', '3.11', '3.12' ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install cz-benchmark with pytest dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt 
          python3 -m pip cache purge

      - name: Pytest
        run: |
          pytest -vv -n2 --dist=loadscope
